# Generated by Django 5.1.3 on 2025-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_scrum_muster_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_automation',
            field=models.BooleanField(default=False, help_text='Indicates if at least two sprints in this project are completed.'),
        ),
    ]
