# Generated by Django 4.2 on 2025-02-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_emotion', models.CharField(max_length=50)),
                ('second_emotion', models.CharField(max_length=50)),
                ('third_emotion', models.CharField(max_length=50)),
                ('average_emotion', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_emotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
