# Generated by Django 4.2 on 2025-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_emotion', models.CharField(max_length=50)),
                ('second_emotion', models.CharField(max_length=50)),
                ('third_emotion', models.CharField(max_length=50)),
                ('average_emotion', models.CharField(max_length=50)),
            ],
        ),
    ]
