# Generated by Django 5.1.3 on 2025-04-17 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemotion',
            name='average_emotion_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemotion',
            name='first_emotion_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemotion',
            name='second_emotion_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemotion',
            name='third_emotion_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyemotion',
            name='average_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyemotion',
            name='first_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyemotion',
            name='second_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyemotion',
            name='third_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='dailyemotion',
            unique_together={('user', 'date')},
        ),
    ]
