# Generated by Django 5.1.7 on 2025-04-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0002_dailyemotion_average_emotion_weight_and_more'),
        ('sprints', '0007_alter_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemotion',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotions', to='sprints.sprint'),
        ),
    ]
