# Generated by Django 5.1.7 on 2025-05-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_detection', '0004_remove_dailyemotion_sprint'),
        ('sprints', '0007_alter_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemotion',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_emotions', to='sprints.sprint'),
        ),
    ]
