# Generated by Django 5.1.3 on 2025-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO DO', 'To Do'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO DO', max_length=15),
        ),
    ]
