# Generated by Django 5.1.3 on 2025-02-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_experience',
        ),
    ]
