# Generated by Django 5.1.3 on 2025-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='story_points',
            new_name='efforts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_duration',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_effort',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('REWORK', 'Rework'), ('DEVOPS', 'DevOps'), ('TESTING', 'Testing')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_complexity',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10),
        ),
    ]
