# Generated by Django 5.1.3 on 2025-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_story_points_task_efforts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='efforts',
        ),
        migrations.AddField(
            model_name='task',
            name='effort',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_effort',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('REWORK', 'Rework'), ('DEVOPS', 'DevOps'), ('TESTING', 'Testing')], default='FE', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_complexity',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10),
        ),
    ]
