# Generated by Django 5.1.3 on 2025-03-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_efforts_task_effort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_effort',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_effort',
        ),
    ]
