# Generated by Django 5.1.3 on 2025-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_actual_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(default='FE', max_length=50),
        ),
    ]
