# Generated by Django 5.1.3 on 2025-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(default='Frontend', max_length=50),
        ),
    ]
