# Generated by Django 5.1.7 on 2025-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='effort',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_effort',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_effort',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
