# Generated by Django 5.1.7 on 2025-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_effort_task_actual_effort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rework_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
