# Generated by Django 5.1.7 on 2025-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_rework_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reactivated',
            field=models.BooleanField(default=False),
        ),
    ]
