# Generated by Django 5.1.7 on 2025-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_is_reactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rework_effort',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
