# Generated by Django 5.1.3 on 2025-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=100)),
                ('developer_experience', models.IntegerField()),
                ('task_name', models.CharField(max_length=255)),
                ('task_duration', models.FloatField()),
                ('task_complexity', models.IntegerField()),
                ('story_points', models.FloatField()),
            ],
        ),
    ]
