# Generated by Django 5.1.7 on 2025-04-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_estimation', '0003_rename_estimation_result_estimation_estimated_effort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='productivity',
        ),
    ]
