# Generated by Django 5.1.7 on 2025-04-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_estimation', '0004_remove_estimation_productivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='created_at',
        ),
    ]
