# Generated by Django 5.1.3 on 2025-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (28, '4 weeks')], default=14)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
