# Generated by Django 5.1.3 on 2025-01-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='goal',
            new_name='sprint_goal',
        ),
    ]
