# Generated by Django 5.1.3 on 2025-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duration',
            field=models.IntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (28, '4 weeks'), (0, 'Custom')], default=14),
        ),
    ]
