# Generated by Django 5.1.3 on 2025-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_alter_sprint_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (28, '4 weeks'), (0, 'Custom')], default=14, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
