# Generated by Django 5.1.3 on 2025-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_alter_sprint_duration_alter_sprint_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
