# Generated by Django 5.1.3 on 2025-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_sprint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
