# Generated by Django 5.1.7 on 2025-04-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_scrum_muster_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(editable=False, max_length=50)),
                ('complexity', models.CharField(editable=False, max_length=20)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('total_actual_effort', models.FloatField(default=0.0)),
                ('rework_count', models.PositiveIntegerField(default=0)),
                ('productivity', models.FloatField(default=0.0)),
                ('rework_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project', 'category', 'complexity')},
            },
        ),
    ]
