# Generated by Django 5.1.7 on 2025-04-16 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_performance', '0001_initial'),
        ('projects', '0003_remove_project_scrum_muster_project_created_by'),
        ('sprints', '0007_alter_sprint_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='developerperformance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='developerperformance',
            name='rework_effort',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='developerperformance',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint'),
        ),
        migrations.AlterUniqueTogether(
            name='developerperformance',
            unique_together={('user', 'project', 'sprint', 'category', 'complexity')},
        ),
    ]
