# Generated by Django 5.1.7 on 2025-04-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_performance', '0002_alter_developerperformance_unique_together_and_more'),
        ('projects', '0003_remove_project_scrum_muster_project_created_by'),
        ('sprints', '0007_alter_sprint_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='developerperformance',
            unique_together={('user', 'sprint', 'project', 'category', 'complexity')},
        ),
        migrations.AlterField(
            model_name='developerperformance',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='developerperformance',
            name='complexity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='developerperformance',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint'),
        ),
        migrations.RemoveField(
            model_name='developerperformance',
            name='rework_count',
        ),
        migrations.RemoveField(
            model_name='developerperformance',
            name='rework_effort',
        ),
        migrations.RemoveField(
            model_name='developerperformance',
            name='rework_rate',
        ),
    ]
