# Generated by Django 5.1.3 on 2025-04-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer_performance', '0003_alter_developerperformance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='developerperformance',
            unique_together=set(),
        ),
    ]
